Redirect most output from prepare func to a `prepare.log` file. This makes it easier for users to report/find patch application failures, and cleans the terminal output up of what could possibly end up as lost bits.

diff --git a/wine-tkg-git/PKGBUILD b/wine-tkg-git/PKGBUILD
--- a/wine-tkg-git/PKGBUILD
+++ b/wine-tkg-git/PKGBUILD
@@ -744,7 +744,10 @@ nonuser_patcher() {
     if [ "$_nopatchmsg" != "true" ]; then
       _fullpatchmsg=" -- ( $_patchmsg )"
     fi
-    msg2 "Applying ${_patchname}" && patch -Np1 < ../"$_patchname" && echo -e "${_patchname}${_fullpatchmsg}" >> "$_where"/last_build_config.log
+    msg2 "Applying ${_patchname}"
+    echo -e "\n${_patchname}${_fullpatchmsg}" >> "$_where"/prepare.log
+    patch -Np1 < ../"$_patchname" >> "$_where"/prepare.log || (error "Patch application has failed. The error was logged to $_where/prepare.log for your convenience." && exit 1)
+    echo -e "${_patchname}${_fullpatchmsg}" >> "$_where"/last_build_config.log
   fi
 }
 
@@ -778,7 +781,7 @@ prepare() {
 	fi
 
 	# prepare steps
-	_source_cleanup
+	_source_cleanup > "$_where"/prepare.log
 	_prepare
 	_makedirs
 }
diff --git a/wine-tkg-git/wine-tkg-patches/hotfixes/hotfixer b/wine-tkg-git/wine-tkg-patches/hotfixes/hotfixer
--- a/wine-tkg-git/wine-tkg-patches/hotfixes/hotfixer
+++ b/wine-tkg-git/wine-tkg-patches/hotfixes/hotfixer
@@ -87,7 +87,8 @@ if (cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor fd7992972b25
               msg2 "Applying reverting hotfix ${_f}"
               msg2 ""
               msg2 "######################################################"
-              patch -Np1 -R < "${_f}"
+              echo -e "\nApplying reverting hotfix ${_f##*/}" >> "$_where"/prepare.log
+              patch -Np1 -R < "${_f}" >> "$_where"/prepare.log || (error "Patch application has failed. The error was logged to $_where/prepare.log for your convenience." && exit 1)
               echo "Applied reverting hotfix ${_f}" >> "$_where"/last_build_config.log
             fi
           done
@@ -109,7 +110,8 @@ if (cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor fd7992972b25
               msg2 "Applying hotfix ${_f}"
               msg2 ""
               msg2 "######################################################"
-              patch -Np1 < "${_f}"
+              echo -e "\nApplying hotfix ${_f##*/}" >> "$_where"/prepare.log
+              patch -Np1 < "${_f}" >> "$_where"/prepare.log || (error "Patch application has failed. The error was logged to $_where/prepare.log for your convenience." && exit 1)
               echo "Applied hotfix ${_f}" >> "$_where"/last_build_config.log
             fi
           done
