Properly exit when failing in user_patcher() and hotfixer()
We were only exiting the subshell

diff --git a/wine-tkg-git/wine-tkg-patches/hotfixes/hotfixer b/wine-tkg-git/wine-tkg-patches/hotfixes/hotfixer
--- a/wine-tkg-git/wine-tkg-patches/hotfixes/hotfixer
+++ b/wine-tkg-git/wine-tkg-patches/hotfixes/hotfixer
@@ -197,7 +197,9 @@ hotfixer() {
     if [ -e "${_f}.${_userpatch_ext}revert" ]; then
       msg2 "## Applying reverting hotfix for ${_userpatch_target}: ${_f##*/}.${_userpatch_ext}revert"
       echo -e "\nApplying reverting hotfix ${_f##*/}.${_userpatch_ext}revert" >> "$_where"/prepare.log
-      patch -Np1 -R < "${_f}.${_userpatch_ext}revert" >> "$_where"/prepare.log || (error "Patch application has failed. The error was logged to $_where/prepare.log for your convenience." && exit 1)
+      if ! patch -Np1 -R < "${_f}.${_userpatch_ext}revert" >> "$_where"/prepare.log; then
+        error "Patch application has failed. The error was logged to $_where/prepare.log for your convenience." && exit 1
+      fi
       echo "Applied reverting hotfix ${_f##*/}.${_userpatch_ext}revert" >> "$_where"/last_build_config.log
     fi
   done
@@ -205,7 +207,9 @@ hotfixer() {
     if [ -e "${_f}.${_userpatch_ext}patch" ]; then
       msg2 "## Applying hotfix for ${_userpatch_target}: ${_f##*/}.${_userpatch_ext}patch"
       echo -e "\nApplying hotfix ${_f##*/}.${_userpatch_ext}patch" >> "$_where"/prepare.log
-      patch -Np1 < "${_f}.${_userpatch_ext}patch" >> "$_where"/prepare.log || (error "Patch application has failed. The error was logged to $_where/prepare.log for your convenience." && exit 1)
+      if ! patch -Np1 < "${_f}.${_userpatch_ext}patch" >> "$_where"/prepare.log; then
+        error "Patch application has failed. The error was logged to $_where/prepare.log for your convenience." && exit 1
+      fi
       echo "Applied hotfix ${_f##*/}.${_userpatch_ext}patch" >> "$_where"/last_build_config.log
     fi
   done
