Hotfixer: Robustness enhancements and fixes  - Introduce the "earlyhotfixer" script, that gets loaded at the time we previously loaded the "normal" hotfixer  - Move early checks (community patches and broken staging upstream commit hotfixing) to "earlyhotfixer" and remove the "early" userpatching from prepare  - Load the hotfixer right before the nonuser_reverter checks, so our sources are correctly checked out ready for reverting work (it was running too early before, leading to potential breakage on legacy)  - Run the hotfixer after the nonuser_reverter so we don't end up with conflicts preventing git to do its job  - Don't set _broken_staging_44d1a45_localreverts="true" unconditionally if esync or fsync is disabled  - Replace the _patches variable by a separate _hotfixes one to contain our hotfixes array. This prevents a potential conflict with userpatches  - Check for the oldest hotfix-needy commit before prompting the user about hotfixes  - Remove unneeded fluff

diff --git a/wine-tkg-git/wine-tkg-patches/hotfixes/hotfixer b/wine-tkg-git/wine-tkg-patches/hotfixes/hotfixer
--- a/wine-tkg-git/wine-tkg-patches/hotfixes/hotfixer
+++ b/wine-tkg-git/wine-tkg-patches/hotfixes/hotfixer
@@ -1,31 +1,12 @@
 #!/bin/bash
 
-# community patches
-if [[ ${_community_patches[*]} =~ "winex11-fs-no_above_state.mypatch" ]]; then
-  if [ "$_proton_fs_hack" != "true" ]; then
+if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor fd7992972b252ed262d33ef604e9e1235d2108c5 HEAD ); then
+  if [ "$_hotfixes_no_confirm" != "true" ]; then
     msg2 ""
-    read -rp "HALP! You have enabled winex11-fs-no_above_state community patch, but its _proton_fs_hack dependency is disabled. Enable _proton_fs_hack?"$'\n> Y/n : ' _hotfixansw;
+    read -rp "HALP! We got some hotfixes for your current tree. Do you want to apply them all with no further prompt?"$'\n> Y/n : ' _hotfixansw;
     if [ "$_hotfixansw" != "n" ] && [ "$_hotfixansw" != "N" ]; then
-      _proton_fs_hack="true"
+      _hotfixes_no_confirm="true"
     fi
-  fi
-fi
-if [[ ${_community_patches[*]} =~ "guy1524_mfplat_WIP.mypatch" ]]; then
-  if [ "$_proton_mf_hacks" = "true" ]; then
-    msg2 ""
-    read -rp "HALP! You have enabled guy1524_mfplat_WIP community patch, but the potentially conflicting _proton_mf_hacks option is also enabled. Disable _proton_mf_hacks?"$'\n> Y/n : ' _hotfixansw;
-    if [ "$_hotfixansw" != "n" ] && [ "$_hotfixansw" != "N" ]; then
-      _proton_mf_hacks="false"
-    fi
-  fi
-fi
-# /community patches
-
-if [ "$_hotfixes_no_confirm" != "true" ]; then
-  msg2 ""
-  read -rp "HALP! We got some hotfixes for your current tree. Do you want to apply them all with no further prompt?"$'\n> Y/n : ' _hotfixansw;
-  if [ "$_hotfixansw" != "n" ] && [ "$_hotfixansw" != "N" ]; then
-    _hotfixes_no_confirm="true"
   fi
 fi
 
@@ -36,53 +17,54 @@ fi
 # https://bugs.winehq.org/show_bug.cgi?id=49098
 # https://bugs.winehq.org/show_bug.cgi?id=49123
 # https://bugs.winehq.org/show_bug.cgi?id=49041
-if (cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor fd7992972b252ed262d33ef604e9e1235d2108c5 HEAD); then
+if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor fd7992972b252ed262d33ef604e9e1235d2108c5 HEAD ); then
   if [ "$_hotfixes_no_confirm" != "true" ]; then
     read -rp "Hotfix: An upstream patchset (starting with fd79929) breaks a large amount of games in various ways (ex: WoW, Overwatch, Star Citizen, Path of Exile etc.). As a temporary fix, this patch reverts it on current HEAD."$'\n> N/y : ' _hotfixansw;
   fi
   if [ "$_hotfixansw" = "y" ] || [ "$_hotfixes_no_confirm" = "true" ]; then
-    if git merge-base --is-ancestor b7b1ad09629a6678383a5ae791a9507c9eb87be3 HEAD >/dev/null 2>&1; then
-      local _patches=("$_where"/wine-tkg-patches/hotfixes/fd799297/fd7992972b252ed262d33ef604e9e1235d2108c5-6)
-    elif git merge-base --is-ancestor d2b70aa57a77103107a2e620999181c518d14bda HEAD >/dev/null 2>&1; then
-      local _patches=("$_where"/wine-tkg-patches/hotfixes/fd799297/fd7992972b252ed262d33ef604e9e1235d2108c5-5)
-    elif git merge-base --is-ancestor 68e675d73db4fb90fff84c0e1f6de3b492061b5f HEAD >/dev/null 2>&1; then
-      local _patches=("$_where"/wine-tkg-patches/hotfixes/fd799297/fd7992972b252ed262d33ef604e9e1235d2108c5-4)
-    elif git merge-base --is-ancestor 6f4272ce3e74f2d30f45bf0d407cdc9264b813a9 HEAD >/dev/null 2>&1; then
-      local _patches=("$_where"/wine-tkg-patches/hotfixes/fd799297/fd7992972b252ed262d33ef604e9e1235d2108c5-3)
-    elif git merge-base --is-ancestor 0a72ec1dacb59c72980c3133fddf316377349048 HEAD >/dev/null 2>&1; then
-      local _patches=("$_where"/wine-tkg-patches/hotfixes/fd799297/fd7992972b252ed262d33ef604e9e1235d2108c5-2)
-    elif git merge-base --is-ancestor fd7992972b252ed262d33ef604e9e1235d2108c5 HEAD >/dev/null 2>&1; then
-      local _patches=("$_where"/wine-tkg-patches/hotfixes/fd799297/fd7992972b252ed262d33ef604e9e1235d2108c5)
+    if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor b7b1ad09629a6678383a5ae791a9507c9eb87be3 HEAD ); then
+      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/fd799297/fd7992972b252ed262d33ef604e9e1235d2108c5-6)
+    elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor d2b70aa57a77103107a2e620999181c518d14bda HEAD ); then
+      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/fd799297/fd7992972b252ed262d33ef604e9e1235d2108c5-5)
+    elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 68e675d73db4fb90fff84c0e1f6de3b492061b5f HEAD ); then
+      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/fd799297/fd7992972b252ed262d33ef604e9e1235d2108c5-4)
+    elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 6f4272ce3e74f2d30f45bf0d407cdc9264b813a9 HEAD ); then
+      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/fd799297/fd7992972b252ed262d33ef604e9e1235d2108c5-3)
+    elif ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 0a72ec1dacb59c72980c3133fddf316377349048 HEAD ); then
+      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/fd799297/fd7992972b252ed262d33ef604e9e1235d2108c5-2)
+    else
+      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/fd799297/fd7992972b252ed262d33ef604e9e1235d2108c5)
     fi
   fi
 fi
 
 # Esync/Fsync killer - mainline reverts
-if ([ "$_use_esync" = "true" ] || [ "$_use_fsync" = "true" ]) && (cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 01150d7f8d27ad5efdb824da938c4a9fa562a036 HEAD); then
+if ( [ "$_use_esync" = "true" ] || [ "$_use_fsync" = "true" ] ) && ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 01150d7f8d27ad5efdb824da938c4a9fa562a036 HEAD ); then
   if [ "$_hotfixes_no_confirm" != "true" ]; then
     read -rp "Hotfix: Upstream commits 01150d7 to e854ea3 broke esync patchset (which has been disabled in staging as a result) leading to fsync getting broken as well. Wanna bring back esync/fsync ?"$'\n> N/y : ' _hotfixansw;
   fi
   if [ "$_hotfixansw" = "y" ] || [ "$_hotfixes_no_confirm" = "true" ]; then
     _hotfix_mainlinereverts=(9fe61171e515e7c77720675ecbe69731219b549c c96ef78b6d6d9184d8ec4cd18924a3049d388583 7c32b2dd9368137eca3cf0202360bbe0db62efbf ac90898f72b02bbc226a95deb40555c1fb8ac3a3 87fa906a84621295a76035d73dd6305c9cd2ea4a c0319e0eabbad87a3e153c23f2461c881153b984 b925dd78b813decf386139a15aa7bc6863ee7ae5 3e9f8c87e5a2acaa80f8bbb1d50fa82147942143 704975f58d7947721f530d202022721c16df466a 04f41e87a369828a698f62c32cabad34ed34a3e7 01150d7f8d27ad5efdb824da938c4a9fa562a036 1a743c9af39d0224b65ae504ae7e24d9fad56c2b 8a63b688ac49f19c259066fd100407edf3747f95 e6e2f2325a0a4eb14f10dd6df319b068761e9600 e854ea34cc481658ec61f4603d0438e075608c98)
     #_hotfix_stagingreverts=()
-    # Esync/Fsync killer - staging unbreak
-    if (cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor a4d98c48f982b52375f0ccefc217984aab936033 HEAD); then
-      _patches+=("$_where"/wine-tkg-patches/hotfixes/01150d7f/06877e55b1100cc49d3726e9a70f31c4dfbe66f8-5)
-    elif (cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor 676f261e5e9959e8fb9fe6266ffd2a29bcda2c0d HEAD); then
-      _patches+=("$_where"/wine-tkg-patches/hotfixes/01150d7f/06877e55b1100cc49d3726e9a70f31c4dfbe66f8-4)
-    elif (cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor c81093882b2b9ce4a5830437cecdc58b8807d29b HEAD); then
-      _patches+=("$_where"/wine-tkg-patches/hotfixes/01150d7f/06877e55b1100cc49d3726e9a70f31c4dfbe66f8-3)
-    elif (cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor f132e60b9db336495acc50f2a31a6aeca8d89de5 HEAD); then
-      _patches+=("$_where"/wine-tkg-patches/hotfixes/01150d7f/06877e55b1100cc49d3726e9a70f31c4dfbe66f8-2)
-    elif (cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor 06877e55b1100cc49d3726e9a70f31c4dfbe66f8 HEAD); then
-      _patches+=("$_where"/wine-tkg-patches/hotfixes/01150d7f/06877e55b1100cc49d3726e9a70f31c4dfbe66f8)
+    # Esync/Fsync killer - staging unbreak - #1
+    if ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor a4d98c48f982b52375f0ccefc217984aab936033 HEAD ); then
+      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/01150d7f/06877e55b1100cc49d3726e9a70f31c4dfbe66f8-5)
+    elif ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor 676f261e5e9959e8fb9fe6266ffd2a29bcda2c0d HEAD ); then
+      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/01150d7f/06877e55b1100cc49d3726e9a70f31c4dfbe66f8-4)
+    elif ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor c81093882b2b9ce4a5830437cecdc58b8807d29b HEAD ); then
+      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/01150d7f/06877e55b1100cc49d3726e9a70f31c4dfbe66f8-3)
+    elif ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor f132e60b9db336495acc50f2a31a6aeca8d89de5 HEAD ); then
+      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/01150d7f/06877e55b1100cc49d3726e9a70f31c4dfbe66f8-2)
+    elif ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor 06877e55b1100cc49d3726e9a70f31c4dfbe66f8 HEAD ); then
+      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/01150d7f/06877e55b1100cc49d3726e9a70f31c4dfbe66f8)
     fi
-    if (cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor 676f261e5e9959e8fb9fe6266ffd2a29bcda2c0d HEAD); then
-      _patches+=("$_where"/wine-tkg-patches/hotfixes/01150d7f/934a09585a15e8491e422b43624ffe632b02bd3c-3)
-    elif (cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor c81093882b2b9ce4a5830437cecdc58b8807d29b HEAD); then
-      _patches+=("$_where"/wine-tkg-patches/hotfixes/01150d7f/934a09585a15e8491e422b43624ffe632b02bd3c-2)
-    elif (cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor 934a09585a15e8491e422b43624ffe632b02bd3c HEAD); then
-      _patches+=("$_where"/wine-tkg-patches/hotfixes/01150d7f/934a09585a15e8491e422b43624ffe632b02bd3c)
+    #2
+    if ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor 676f261e5e9959e8fb9fe6266ffd2a29bcda2c0d HEAD ); then
+      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/01150d7f/934a09585a15e8491e422b43624ffe632b02bd3c-3)
+    elif ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor c81093882b2b9ce4a5830437cecdc58b8807d29b HEAD ); then
+      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/01150d7f/934a09585a15e8491e422b43624ffe632b02bd3c-2)
+    elif ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor 934a09585a15e8491e422b43624ffe632b02bd3c HEAD ); then
+      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/01150d7f/934a09585a15e8491e422b43624ffe632b02bd3c)
     fi
   else
     _broken_staging_44d1a45_localreverts="true"
@@ -90,54 +72,40 @@ if ([ "$_use_esync" = "true" ] || [ "$_use_fsync" = "true" ]) && (cd "${srcdir}"
     _use_fsync="false"
     _proton_rawinput="false"
   fi
-else
+elif ( [ "$_use_esync" != "true" ] || [ "$_use_fsync" != "true" ] ) && ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 01150d7f8d27ad5efdb824da938c4a9fa562a036 HEAD ); then
   _broken_staging_44d1a45_localreverts="true"
 fi
 
 # WINEDEBUG crash - legacy
-if (cd "${srcdir}"/"${_stgsrcdir}" && ! git merge-base --is-ancestor a1bda115af8ad3484b7c17eac7da74e4906fa9e4 HEAD); then
+if ( cd "${srcdir}"/"${_stgsrcdir}" && ! git merge-base --is-ancestor a1bda115af8ad3484b7c17eac7da74e4906fa9e4 HEAD ); then
   if [ "$_hotfixes_no_confirm" != "true" ]; then
     read -rp "Hotfix: Upstream commits cd215bb to ca13f48 are interacting badly with WINEDEBUG env var and break staging. Are you okay to revert them ?"$'\n> N/y : ' _hotfixansw;
   fi
   if [ "$_hotfixansw" = "y" ] || [ "$_hotfixes_no_confirm" = "true" ]; then
     _hotfix_mainlinereverts=(cd215bb49bc240cdce5415c80264f8daa557636a 8ca9e0b1abba7640e288df7b55b60903bc52fc9d 6a1667fab428764eeaba38ac9b5cb1813c5cffda 9b12068c6c8ba656e8ca768227b1a970877d4730 cc5953048e570155deb791b9e9e738a0508c2032 0936606c383744daa8be046db72e8e888522ce21 ca13f489e18fb1f7944e3bdcfdfc4a810bf80994)
-    _patches+=("$_where"/wine-tkg-patches/hotfixes/a1bda115/acd209d6039f2492bdc8aca3d15bb1b268b04f1a)
+    _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/a1bda115/acd209d6039f2492bdc8aca3d15bb1b268b04f1a)
     # Staging conflict
-    if (cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor 4501d49149e37b37edd61f8a1694930db7418a61 HEAD); then
-      _patches+=("$_where"/wine-tkg-patches/hotfixes/a1bda115/4501d49149e37b37edd61f8a1694930db7418a61)
+    if ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor 4501d49149e37b37edd61f8a1694930db7418a61 HEAD ); then
+      _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/a1bda115/4501d49149e37b37edd61f8a1694930db7418a61)
     fi
   fi
 fi
 
-# Broken staging fbe1ba5 - legacy
-if ( cd "${srcdir}"/"${_stgsrcdir}" && [ "$(git rev-parse HEAD)" = "fbe1ba5578fb7380e2b09a5aebf5aa488744a823" ] ); then
-  msg2 "Fix wrong staging upstream commit - Should be 4358ddc75fbfabdc4a4f31b4e3cc9aa1e0811d4c"
-  sed -i 's|echo "3bb824f98891e8eb907c9c652fe528373a17b10d"|echo "4358ddc75fbfabdc4a4f31b4e3cc9aa1e0811d4c"|g' "${srcdir}"/"${_stgsrcdir}"/patches/patchinstall.sh
-fi
-
-# Broken staging f329843 - legacy
-if ( cd "${srcdir}"/"${_stgsrcdir}" && [ "$(git rev-parse HEAD)" = "f3298432f0c4614a7554e06c6c9a66ef3623ead8" ] ); then
-  msg2 "Fix wrong staging upstream commit - Should be 8257fe88fb99ca0bdeec27b47b7cf835bda5c061"
-  sed -i 's|echo "ba920246e502afe7bc664c1881d528a27e980101"|echo "8257fe88fb99ca0bdeec27b47b7cf835bda5c061"|g' "${srcdir}"/"${_stgsrcdir}"/patches/patchinstall.sh
-fi
-
 hotfixer() {
-  if [ ${#_patches[@]} -ge 2 ] || [ -e "${_patches}" ]; then
-    for _f in "${_patches[@]}"; do
-      if [ -e "${_f}.${_userpatch_ext}revert" ]; then
-        msg2 "## Applying reverting hotfix ${_f}.${_userpatch_ext}revert ##"
-        echo -e "\nApplying reverting hotfix ${_f##*/}.${_userpatch_ext}revert" >> "$_where"/prepare.log
-        patch -Np1 -R < "${_f}.${_userpatch_ext}revert" >> "$_where"/prepare.log || (error "Patch application has failed. The error was logged to $_where/prepare.log for your convenience." && exit 1)
-        echo "Applied reverting hotfix ${_f}.${_userpatch_ext}revert" >> "$_where"/last_build_config.log
-      fi
-    done
-    for _f in "${_patches[@]}"; do
-      if [ -e "${_f}.${_userpatch_ext}patch" ]; then
-        msg2 "## Applying hotfix ${_f}.${_userpatch_ext}patch ##"
-        echo -e "\nApplying hotfix ${_f##*/}.${_userpatch_ext}patch" >> "$_where"/prepare.log
-        patch -Np1 < "${_f}.${_userpatch_ext}patch" >> "$_where"/prepare.log || (error "Patch application has failed. The error was logged to $_where/prepare.log for your convenience." && exit 1)
-        echo "Applied hotfix ${_f}.${_userpatch_ext}patch" >> "$_where"/last_build_config.log
-      fi
-    done
-  fi
+  for _f in "${_hotfixes[@]}"; do
+    if [ -e "${_f}.${_userpatch_ext}revert" ]; then
+      msg2 "## Applying reverting hotfix for ${_userpatch_target}: ${_f##*/}.${_userpatch_ext}revert"
+      echo -e "\nApplying reverting hotfix ${_f##*/}.${_userpatch_ext}revert" >> "$_where"/prepare.log
+      patch -Np1 -R < "${_f}.${_userpatch_ext}revert" >> "$_where"/prepare.log || (error "Patch application has failed. The error was logged to $_where/prepare.log for your convenience." && exit 1)
+      echo "Applied reverting hotfix ${_f##*/}.${_userpatch_ext}revert" >> "$_where"/last_build_config.log
+    fi
+  done
+  for _f in "${_hotfixes[@]}"; do
+    if [ -e "${_f}.${_userpatch_ext}patch" ]; then
+      msg2 "## Applying hotfix for ${_userpatch_target}: ${_f##*/}.${_userpatch_ext}patch"
+      echo -e "\nApplying hotfix ${_f##*/}.${_userpatch_ext}patch" >> "$_where"/prepare.log
+      patch -Np1 < "${_f}.${_userpatch_ext}patch" >> "$_where"/prepare.log || (error "Patch application has failed. The error was logged to $_where/prepare.log for your convenience." && exit 1)
+      echo "Applied hotfix ${_f##*/}.${_userpatch_ext}patch" >> "$_where"/last_build_config.log
+    fi
+  done
 }
