On hotfixing failure, inform the user about the last known good commits for both mainline and staging and which option to change in their .cfg

diff --git a/wine-tkg-git/wine-tkg-patches/hotfixes/hotfixer b/wine-tkg-git/wine-tkg-patches/hotfixes/hotfixer
--- a/wine-tkg-git/wine-tkg-patches/hotfixes/hotfixer
+++ b/wine-tkg-git/wine-tkg-patches/hotfixes/hotfixer
@@ -61,6 +61,9 @@ if ( [ "$_staging_esync" = "true" ] || [ "$_use_esync" = "true" ] || [ "$_use_fs
       _staging_args+=(-W ntdll-SystemRoot_Symlink)
     fi
 
+    _last_known_good_mainline=01bacebba418bf6f58a644b1aab41be215bd200a
+    _last_known_good_staging=4125a9880cf471d2c49fc210a760f2cdffffa9f2
+
     # staging unbreak - #1
     if ( cd "${srcdir}"/"${_stgsrcdir}" && git merge-base --is-ancestor 4125a9880cf471d2c49fc210a760f2cdffffa9f2 HEAD ); then
       _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/01150d7f/06877e55b1100cc49d3726e9a70f31c4dfbe66f8-93)
@@ -414,7 +417,10 @@ hotfixer() {
       msg2 "## Applying reverting hotfix for ${_userpatch_target}: ${_f##*/}.${_userpatch_ext}revert"
       echo -e "\nApplying reverting hotfix ${_f##*/}.${_userpatch_ext}revert" >> "$_where"/prepare.log
       if ! patch -Np1 -R < "${_f}.${_userpatch_ext}revert" >> "$_where"/prepare.log; then
-        error "Patch application has failed. The error was logged to $_where/prepare.log for your convenience." && exit 1
+        error "Patch application has failed. The error was logged to $_where/prepare.log for your convenience."
+        msg2 "To use the last known good mainline version, please set _plain_version=\"$_last_known_good_mainline\" in your .cfg"
+        msg2 "To use the last known good staging version, please set _staging_version=\"$_last_known_good_staging\" in your .cfg (requires _use_staging=\"true\")"
+        exit 1
       fi
       echo "Applied reverting hotfix ${_f##*/}.${_userpatch_ext}revert" >> "$_where"/last_build_config.log
     fi
@@ -424,7 +430,10 @@ hotfixer() {
       msg2 "## Applying hotfix for ${_userpatch_target}: ${_f##*/}.${_userpatch_ext}patch"
       echo -e "\nApplying hotfix ${_f##*/}.${_userpatch_ext}patch" >> "$_where"/prepare.log
       if ! patch -Np1 < "${_f}.${_userpatch_ext}patch" >> "$_where"/prepare.log; then
-        error "Patch application has failed. The error was logged to $_where/prepare.log for your convenience." && exit 1
+        error "Patch application has failed. The error was logged to $_where/prepare.log for your convenience."
+        msg2 "To use the last known good mainline version, please set _plain_version=\"$_last_known_good_mainline\" in your .cfg"
+        msg2 "To use the last known good staging version, please set _staging_version=\"$_last_known_good_staging\" in your .cfg (requires _use_staging=\"true\")"
+        exit 1
       fi
       echo "Applied hotfix ${_f##*/}.${_userpatch_ext}patch" >> "$_where"/last_build_config.log
     fi
