Add basic ntsync5 support for mainline, with header check and quirks
https://repo.or.cz/wine/zf.git/shortlog/refs/heads/ntsync5

diff --git a/wine-tkg-git/wine-tkg-patches/misc/fastsync/fastsync b/wine-tkg-git/wine-tkg-patches/misc/fastsync/fastsync
--- a/wine-tkg-git/wine-tkg-patches/misc/fastsync/fastsync
+++ b/wine-tkg-git/wine-tkg-patches/misc/fastsync/fastsync
@@ -71,4 +71,33 @@
 	    _patchname='fastsync-clock_monotonic-fixup.patch' && _patchmsg="Applied fastsync fix due clock_monotonic" && nonuser_patcher
 	  fi
 
+	elif [ "$_use_ntsync" = "true" ]; then
+
+	  # check Linux headers
+	  ntsync_header_check=$(echo '#include <linux/ntsync.h>' | gcc -H -E -fsyntax-only - 2>&1 | head -n1 | cut -d' ' -f2-)
+	  if [[ ! -s $ntsync_header_check ]]; then
+	    error $ntsync_header_check
+	    error "NTsync header was not found. Build is forcibly prevented."
+	    error 'Please use linux-tkg build with _ntsync="true" or https://aur.archlinux.org/packages/ntsync-dkms/'
+	    exit 1
+	  fi
+
+	  if [ "$_use_staging" = "true" ]; then
+	    error "NTsync for Staging trees isn't available at this point in time. Build is forcibly prevented. Please set _use_staging to false, or fallback to a different synchronization patchset"
+	    exit 1
+	  fi
+
+	  if [ "$_protonify" = "true" ]; then
+	    error "NTsync isn't compatible with enabled _protonify at this point in time. Build is forcibly prevented. Please disable it in your .cfg to use NTsync"
+	    exit 1
+	  fi
+
+	  if [ "$_use_esync" = "false" ] && [ "$_use_fsync" = "false" ] && [ "$_use_fastsync" = "false" ]; then
+	    if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 59485f00c917061c097c1805d7fa7f61c380c749 HEAD ); then
+	      _patchname='ntsync5.patch' && _patchmsg="Using ntsync patchset" && nonuser_patcher
+	    fi
+	  else
+	    error "NTsync for Plain trees conflicts with _use_esync, _use_fsync and _use_fastsync. Build is forcibly prevented. Please disable them in your .cfg to use NTsync"
+	    exit 1
+	  fi
 	fi
